### ISSUE TITLE
SocketIOServer with Spring Boot RESTful API on the same port 8080

### ISSUE THREAD

**Issue by radhakrishna67** [mrniko/netty-socketio#1011]
I am trying to include netty-socketio in spring boot RESTful API application and am trying to run it on the same port.
I am not successful this approach.
Is it possible to run the both netty-socketio and spring boot on the same port?

**Comment by avrilft** [comment]
You can use "https://github.com/trinopoty/socket.io-server-java"

**Comment by radhakrishna67** [comment]
@avrilft I have to run spring boot restful API along with netty-socketio server in the same apache tomcat on the port 443 in the production. Not like restful api on 443 and netty socketio on 8443 in the production

**Comment by avrilft** [comment]
If you're using springboot, check out the following examples. This example socketio service with springboot embedded tomcat to use the same port, the code below USES the library "https://github.com/trinopoty/socket.io-server-java"
`  <dependency>
    <groupId>io.socket</groupId>
    <artifactId>socket.io-server</artifactId>
    <version>4.0.1</version>
  </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-websocket</artifactId>
    </dependency>
`xml

`
public class WebSocketConfig extends BaseController {

    private final static Logger logger = LoggerFactory.getLogger(WebSocketConfig.class);

    @Autowired
    private AuthService authService;

    @Bean
    public ServerEndpointExporter serverEndpointExporter() {
        return new ServerEndpointExporter();
    }

    @Bean(destroyMethod = "shutdown")
    public EngineIoServer engineIoServer() {
        EngineIoServer engine = new EngineIoServer();
        return engine;
    }

    @Bean
    public SocketIoServer socketIoServer() {
        return new SocketIoServer(engineIoServer());
    }

    @Bean
    @Qualifier("/")
    public SocketIoNamespace socketIoNamespace() {
        SocketIoNamespace name = socketIoServer().namespace("/");
        return name;
    }


}
`
`public class WebSocketController {

    private final static Logger logger = LoggerFactory.getLogger(WebSocketController.class);

    private final static String USER_PROPERTIES_WEB_SOCKET = "$$USER_PROPERTIES_WEB_SOCKET";

    private static EngineIoServer engineIoServer;

    @OnOpen
    public void onOpen(Session session, EndpointConfig config, @PathParam("token") String token) throws IOException {
        WebSocketIO socket = new WebSocketIO(session);
        session.getUserProperties().put(USER_PROPERTIES_WEB_SOCKET, socket);
        engineIoServer.handleWebSocket(socket);
    }

    @OnClose
    public void onClose(Session session, CloseReason closeReason) {
        WebSocketIO socket = (WebSocketIO) session.getUserProperties().get(USER_PROPERTIES_WEB_SOCKET);
        if (socket != null) {
            socket.close();
        }
    }

    @OnError
    public void onError(Session session, Throwable e) {
        WebSocketIO socket = (WebSocketIO) session.getUserProperties().get(USER_PROPERTIES_WEB_SOCKET);
        if (socket != null) {
            socket.sendError(e);
        }
    }

    @Autowired
    public void setEngineIoServer(EngineIoServer engineIoServer) {
        WebSocketController.engineIoServer = engineIoServer;
    }
}`

**Comment by nicsor** [comment]
you can do it with some tweaks:

duplicate this class from the library: SocketIOChannelInitializer

and add a custom handler just before PACKET_HANDLER:
https://github.com/mrniko/netty-socketio/blob/65246f30753379a6226a68187977755a851a5f8b/src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java#L184
=> something like:  `pipeline.addLast(HTTP_REQUEST_HANDER, httpRequestHandler);`


then use that custom class when initializing the socketio object:
```
        SocketIOServer server = new SocketIOServer(config);
        server.setPipelineFactory(new SocketIOChannelInitializerCustom());
```

httpRequestHandler mentioned earlier would be a custom class that implements SimpleChannelInboundHandler<FullHttpRequest> 
and in which you override channelRead0:

```
public class HttpRequestHandler extends SimpleChannelInboundHandler<FullHttpRequest> {
    @Override
    protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest fullHttpRequest) throws Exception {
        // look at the path in fullHttpRequest if you want to handle it,
        if (will handle) {
              // add code here to prepare response
                ctx.writeAndFlush(response);
        } else {
            ctx.fireChannelRead(fullHttpRequest.retain());
        }
    }
}
```

worked for me :)

**Comment by itineric** [comment]
@nicsor , the tricky part of your example is here:
```
if (will handle) {
  // add code here to prepare response
  ctx.writeAndFlush(response);
}
```

at that point, how can you redirect the netty "request" to a servlet request internally?

**Comment by tomomoto** [comment]
@nicsor This looks like a dirty hack rather than an adding the required functionality, since ``SockerIOServer``'s ``setPipelineFactory`` requires ``SocketIOChannelInitializer`` and in this case the only way to go with your approach is to extend ``SocketIOChannelInitializer`` and to reimplement (copy-paste) all the methods inside of the custom socket io channel initializer with editing necessary method (``addSocketioHandlers``).

But in any case this change doesen't even work, I've tested a simple proxy `HttpRequestHandler` with your approach
```
public class HttpRequestHandler extends SimpleChannelInboundHandler<FullHttpRequest> {
    @Override
    protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest fullHttpRequest) {
        ctx.fireChannelRead(fullHttpRequest.retain());
    }
}
```
it works if you specify different port of spring boot server app and just does nothing, and fails to start if you specifies the same port as the spring boot application.

The fail is:


```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2025-06-11T23:23:16.834+03:00 ERROR 3056 --- [SpringBootApp] [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8084 was already in use.

Action:

Identify and stop the process that's listening on port 8084 or configure this application to listen on another port.
```

**Comment by tomomoto** [comment]
It shows, that the problem is not how ``SocketIOServer`` is configured internally (by adding handlers, customizing the internal pipelines etc), but how spring threats that port is busy and how socket server takes a port. I suppose, that spring determines ``SocketIOServer`` as a foreign component, which can be inregrated in a spring infrastructure (via ``@Bean``, ``@Component`` etc).
This allows spring to use ``SocketIOServer``, but ``SocketIOServer`` knows nothing about spring.
Probably, the problem is that ``SocketIOServer`` is not aware of spring context generally or/and spring is unable to gracefully determine and integrate ``SocketIOServer`` usage.

**Comment by tomomoto** [comment]
The spring fail was made during startup phase, so spring handles the situation with same ports and fails the init.
In case of `server.start()` call after the spring initialization phase completes, I got the following error:
```
java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.bind(Net.java:511) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:335) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:297) ~[na:na]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141) ~[netty-transport-4.1.121.Final.jar:4.1.121.Final]
```
This indicates, that in current implementation `SocketIOServer` physically request for a separate socket to handle the requests.
It is just impossible to use one port for two sockets.

**Comment by nicsor** [comment]
@tomomoto  I think it was clear it was a hack, if you re-read my comment. And, I don't think there is anything wrong with that.
this workaround lets you call the same mechanism, it does not inject itself in spring.
my goal wasn't to run `spring and netty-socketio` on the same port. it was to have `rest and socket io` on the same port. you can have spring on another port as well, but it would be basically the same functionality. you might as well use a spring router.

If you add the changes above, you can at least debug and see if you can develop it further, the purpose of the handler is to "handle what it can" and "provide an exit" from the pipeline, or continue as before with socket io.
What I did not explain was how to "handle what it can".

@itineric 
I won't provide a full working demo, but, here's the way I did it:
in channelRead0, create a `HttpServletRequest` from `fullHttpRequest`. use `MockHttpServletRequest` for that.

Once you have the `HttpServletRequest`, use `org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping` on it:

`org.springframework.web.servlet.HandlerExecutionChain chain = requestMappingHandlerMapping.getHandler(request);`
if chain is not null, then you can get a handler from that which you can call using:
`org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter` => `handle(request, response, handler);`
reponse can be created from `MockHttpServletResponse`. obviously, request/response need to extend the mock a bit, but it's mostly setters and getters. most complex is to add a content buffer

I said it can be done, and it can. not that it was clean as simply calling a function.
you would still need to add some special cases for `option` requests, and other checks. But that's basically all
