### ISSUE TITLE
where can i set MAX_CONTENT_LENGTH? 

### ISSUE THREAD

**Issue by scriptExplorer** [mrniko/netty-socketio#112]
I use netty-socket.io send big  message, but throw exception:

Apr 2, 2014 8:57:27 PM com.corundumstudio.socketio.handler.PacketHandler exceptionCaught
SEVERE: Exception occurs
io.netty.handler.codec.CorruptedFrameException: Max frame length of 65536 has been exceeded.
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:420)
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:236)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:362)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:139)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:695)

And i try this code : config.setMaxHttpContentLength(64 \* 1024 \* 100);
but does not work it throw the same exception : Max frame length of 65536 has been exceeded.

Where can I set the MAX_CONTENT_LENGTH ?

**Comment by Berg-it** [comment]
I had the same issue 

> Max frame length of 65536 has been exceeded
So I change the code like bellow #: 
```
     Configuration vConfig = new Configuration();
     vConfig.setMaxFramePayloadLength(131072 );
```

But I got the error bellow:

> io.netty.handler.codec.TooLongFrameException: WebSocketFrame length exceeded CompositeByteBuf(freed, components=1) bytes.
