### ISSUE TITLE
Pooling connections which never timeout

### ISSUE THREAD

**Issue by dawe7** [mrniko/netty-socketio#146]
Hi,
I have problem with connections which stay at transport pooling and never switch to websocket transport.

If browser have problem with CORS, then I have for 1 user hundreds of connections which never timeout. :/ The connection stay in this state:  isChannelOpen:false, getTransport:POLLING.

You can simulate this problem by CURL - just create a 1. request to socket IO server:

```
curl --connect-timeout 2 -L 'http://myserver.com:20443/socket.io/?myparam1=XY&myparam2=123&EIO=2&transport=polling&t=1407835214929-0' > /dev/null
```

Then when you check connected clients, this connection never timeout :/
This causes, that my socketIO server once a day run out of memory :/

I found that problem with CORS has only a few of FireFox users. And usually thay have opened FF many days. I didn't find why they have problem with CORS. I will check it. But the main problem are the connections which never timeout :(

This is a log from browser, where you can see, that connection to "myserver.com" timeout, but the connection on server was created.

```
"socket.io-client:url parse http://myserver.com:20443 +0ms" socket.io.js:1258
"socket.io-client new io instance for http://myserver.com:20443 +0ms" socket.io.js:1258
"socket.io-client:manager readyState closed +0ms" socket.io.js:1258
"socket.io-client:manager opening http://myserver.com:20443 +0ms" socket.io.js:1258
"engine.io-client:socket creating transport "polling" +0ms" socket.io.js:1258
"engine.io-client:polling polling +0ms" socket.io.js:1258
"engine.io-client:polling-xhr xhr poll +0ms" socket.io.js:1258
"engine.io-client:polling-xhr xhr open GET: http://myserver.com:20443/socket.io/?nl_user_id=1286029&nl_phone_extension=20931&EIO=2&transport=polling&t=1409054107046-0 +0ms" socket.io.js:1258
"engine.io-client:polling-xhr xhr data null +0ms" socket.io.js:1258
"engine.io-client:socket setting transport polling +2ms" socket.io.js:1258
"socket.io-client:manager connect attempt will timeout after 20000 +3ms" socket.io.js:1258
"socket.io-client:manager readyState opening +0ms" socket.io.js:1258
"socket.io-client:manager connect attempt timed out after 20000 +20s" socket.io.js:1258
"engine.io-client:socket socket close with reason: "forced close" +20s" socket.io.js:1258
"engine.io-client:polling transport not open - deferring close +20s" socket.io.js:1258
"engine.io-client:socket socket closing - telling transport to close +1ms" socket.io.js:1258
"socket.io-client:manager connect_error +3ms" socket.io.js:1258
"socket.io-client:manager will wait 1000ms before reconnect attempt +0ms" socket.io.js:1258
"socket.io-client:manager attempting reconnect +1s" socket.io.js:1258
"socket.io-client:manager readyState closed +0ms" socket.io.js:1258
"socket.io-client:manager opening http://myserver.com:20443 +0ms" socket.io.js:1258
"engine.io-client:socket creating transport "polling" +1s" socket.io.js:1258
"engine.io-client:polling polling +1s" socket.io.js:1258
"engine.io-client:polling-xhr xhr poll +21s" socket.io.js:1258
"engine.io-client:polling-xhr xhr open GET: http://myserver.com:20443/socket.io/?myparam1=XY&myparam2&EIO=2&transport=polling&t=1409054128094-1 +1ms" socket.io.js:1258
"engine.io-client:polling-xhr xhr data null +0ms" socket.io.js:1258
"engine.io-client:socket setting transport polling +2ms" socket.io.js:1258
"socket.io-client:manager connect attempt will timeout after 20000 +3ms"
```

**Comment by blogsit** [comment]
client code:
		var socket =  io.connect('http://dev3.ebooking.qunar.com:8888',{"path" : "/epush"});

		socket.on('connect', function() {
			output('<span class="connect-msg">Client has connected to the server!</span>');
			socket.emit('connectEvent', {username: "kfoj2400",bizType:"eb",pageAddr:"1001"});
		});
server code:
  server.addEventListener("connectEvent", ClientConnectModel.class, new     DataListener<ClientConnectModel>() {
            @Override
            public void onData(SocketIOClient client, ClientConnectModel data, AckRequest ackRequest) {………………
}
}
This code 			socket.emit('connectEvent', {username: "kfoj2400",bizType:"eb",pageAddr:"1001"});
 
error info 

[nioEventLoopGroup-3-8] INFO com.qunar.hotel.epush.servlet.EPushServer - EPushServer Disconnect:SessionId=1aa733ab-d5f0-476e-a935-1951a8163ae6disconnect_time:1426057478145
[nioEventLoopGroup-3-2] INFO com.qunar.hotel.epush.servlet.EPushServer - EPushServer connected:SessionId=78a9c77c-db4e-4b44-9fa7-75d2a3ce3371connect_time:1426057717679
[nioEventLoopGroup-3-5] ERROR com.corundumstudio.socketio.handler.InPacketHandler - Error during data processing. Client sessionId: 78a9c77c-db4e-4b44-9fa7-75d2a3ce3371, data: 3:42["connectEvent",{"username":"kfoj2400","bizType":"eb","pageAddr":1001}]
java.lang.IllegalStateException
        at com.corundumstudio.socketio.protocol.PacketType.valueOf(PacketType.java:48)
        at com.corundumstudio.socketio.protocol.PacketDecoder.readType(PacketDecoder.java:85)
        at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:132)
        at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:114)
        at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
        at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:187)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at com.corundumstudio.socketio.transport.PollingTransport.onPost(PollingTransport.java:161)
        at com.corundumstudio.socketio.transport.PollingTransport.handleMessage(PollingTransport.java:120)
        at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:97)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:115)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:619)

**Comment by kun2000** [comment]
Try the lastest socket.io client js
