### ISSUE TITLE
Too many open files - io.netty.channel.DefaultChannelPipeline

### ISSUE THREAD

**Issue by dawe7** [mrniko/netty-socketio#171]
Once a week we have in log this error:

```[nioEventLoopGroup-2-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usuall
y means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:135)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:68)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)```

We checked that at that time we had opened about 2000 files and about 4000 network connections. The limit for 1 user in linux we have about 16000 files :/

Can you help me how catch this exception? When I can catch it, then I can call System.exit(1); and then we run a new instance of server. In current situation just some thread is down, and out server doesn't work properly :/

Thank you,
D.

**Comment by mrniko** [comment]
This issue also related to ''silent connection" attack https://github.com/mrniko/netty-socketio/commit/3e926dde39cd92b15d0e9db0f72c562a529b0a52

**Comment by jkohjk** [comment]
I have been encountering the same problem. My concurrent number of users is not high, but the number of connections and therefore the number of file handles increases over time. I added some logging and monitored the connections / file handles to pinpoint the issue and tested 3 situations : 
1. from server, getting the SocketIOClient and calling disconnect
1. calling disconnect from client
1. turning off internet on client

In the first 2 cases, `WebSocketTransport.channelInactive` calls `ClientHead.onChannelDisconnect`. In the 3rd case, the Runnable in `ClientHead.schedulePingTimeout` calls `ClientHead.onChannelDisconnect`. `WebSocketTransport.channelInactive` was never called which means the channel was not disconnected from netty. 

I fixed this by changing the Runnable in `ClientHead.schedulePingTimeout` to call `ClientHead.disconnect` instead. It worked for my use case, I'm not sure if works for other situations as well.

**Comment by pablojr** [comment]
Would you mind providing your patch so it could be considered for eventual merging? Thanks.
