### ISSUE TITLE
socket.emit(**) error info

### ISSUE THREAD

**Issue by blogsit** [mrniko/netty-socketio#220]
client code:
var socket = io.connect('http://dev3.ebooking.qunar.com:8888',{"path" : "/epush"});

    socket.on('connect', function() {
        output('<span class="connect-msg">Client has connected to the server!</span>');
        socket.emit('connectEvent', {username: "kfoj2400",bizType:"eb",pageAddr:"1001"});
    });
server code:

server.addEventListener("connectEvent", ClientConnectModel.class, new DataListener() {
@Override
public void onData(SocketIOClient client, ClientConnectModel data, AckRequest ackRequest) {………………
}
}
This code socket.emit('connectEvent', {username: "kfoj2400",bizType:"eb",pageAddr:"1001"});

error info

[nioEventLoopGroup-3-8] INFO com.qunar.hotel.epush.servlet.EPushServer - EPushServer Disconnect:SessionId=1aa733ab-d5f0-476e-a935-1951a8163ae6disconnect_time:1426057478145
[nioEventLoopGroup-3-2] INFO com.qunar.hotel.epush.servlet.EPushServer - EPushServer connected:SessionId=78a9c77c-db4e-4b44-9fa7-75d2a3ce3371connect_time:1426057717679
[nioEventLoopGroup-3-5] ERROR com.corundumstudio.socketio.handler.InPacketHandler - Error during data processing. Client sessionId: 78a9c77c-db4e-4b44-9fa7-75d2a3ce3371, data: 3:42["connectEvent",{"username":"kfoj2400","bizType":"eb","pageAddr":1001}]
java.lang.IllegalStateException
at com.corundumstudio.socketio.protocol.PacketType.valueOf(PacketType.java:48)
at com.corundumstudio.socketio.protocol.PacketDecoder.readType(PacketDecoder.java:85)
at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:132)
at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:114)
at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:187)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
at com.corundumstudio.socketio.transport.PollingTransport.onPost(PollingTransport.java:161)
at com.corundumstudio.socketio.transport.PollingTransport.handleMessage(PollingTransport.java:120)
at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:97)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:115)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
at java.lang.Thread.run(Thread.java:619)

**Comment by blogsit** [comment]
upgrade netty-socketio-1.7.7   fix

**Comment by mrniko** [comment]
so is it working now?

**Comment by blogsit** [comment]
yes   is  ok

**Comment by MincoTse** [comment]
![image](https://user-images.githubusercontent.com/21156710/67284800-e01c3800-f508-11e9-925b-2830ec1ac820.png)
相同的错误 又出现了
