### ISSUE TITLE
push message have  error,what can I do ?help

### ISSUE THREAD

**Issue by blogsit** [mrniko/netty-socketio#228]
io.netty.handler.codec.DecoderException: HttpRequestDecoder.decode() did not read anything but decoded a message.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:287) ~[netty-codec-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) ~[netty-codec-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by pablojr** [comment]
First of all, I would suggest you improve your post, giving more details about your environment and application (i.e. Java version, netty-socketio version, OS, if you're using an app container) and what you're trying to achieve with socket.io that leads to this error happening.
Please remember that this group/forum is comprised of software developers, not magicians or fortune tellers that can see the future!

**Comment by mrniko** [comment]
@blogsit 

setup a logging level to 'trace' mode. this will show you a packet causes this error

**Comment by blogsit** [comment]
@mrniko   thanks     
now  I have  new  problem，  socket can't disconnection , Do load balancing three virtual machine, the machine configuration is 8 gb of memory, Occasional connection can't disconnection, continually restart server connections will be normal

**Comment by blogsit** [comment]
use netty socket.io version 1.7.7     socket.io  version 1.3.5
