### ISSUE TITLE
netty-socketio under Tomcat running,press ctrl C stop Tomcat, Console print error 

### ISSUE THREAD

**Issue by 617726909** [mrniko/netty-socketio#237]
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-2-1] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-3-1] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [pool-4-thread-1] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-3-2] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-3-3] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-3-4] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-3-5] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [nioEventLoopGroup-3-6] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [FileWatchdog] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
严重: The web application [] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
严重: The web application [] created a ThreadLocal with key of type [com.corundumstudio.socketio.protocol.JacksonJsonSupport$ByteArraySerializer$1] (value [com.corundumstudio.socketio.protocol.JacksonJsonSupport$ByteArraySerializer$1@e56380a]) and a value of type [java.util.ArrayList] (value [[]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
五月 26, 2015 10:10:03 上午 org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
严重: The web application [] created a ThreadLocal with key of type [com.corundumstudio.socketio.protocol.JacksonJsonSupport$ByteArraySerializer$1] (value [com.corundumstudio.socketio.protocol.JacksonJsonSupport$ByteArraySerializer$1@e56380a]) and a value of type [java.util.ArrayList] (value [[]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Exception in thread "nioEventLoopGroup-2-1" java.lang.NoClassDefFoundError: io/n
etty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.DefaultPro
mise$2
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoa
der.java:1720)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoa
der.java:1571)
        ... 5 more
Exception in thread "nioEventLoopGroup-2-2" java.lang.NoClassDefFoundError: io/n
etty/util/concurrent/DefaultPromise$2
Exception in thread "nioEventLoopGroup-2-5" Exception in thread "nioEventLoopGro
up-2-7" Exception in thread "nioEventLoopGroup-2-4" Exception in thread "nioEven
tLoopGroup-2-8" Exception in thread "nioEventLoopGroup-2-6" Exception in thread
"nioEventLoopGroup-2-3"         at io.netty.util.concurrent.DefaultPromise.notif
yListeners(DefaultPromise.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromis
e.java:589)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.jav
a:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:155)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)

**Comment by mrniko** [comment]
> java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise

Please check your classpath
