### ISSUE TITLE
Failed to fail the promise because it's done already

### ISSUE THREAD

**Issue by asktalk** [mrniko/netty-socketio#302]
[nioEventLoopGroup-3-5] WARN io.netty.channel.DefaultChannelPipeline - Failed to fail the promise because it's done already: DefaultChannelPromise@5c956e2a(success)
java.lang.IllegalStateException: complete already: DefaultChannelPromise@5c956e2a(success)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:400)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:76)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:71)
	at com.corundumstudio.socketio.handler.EncoderHandler.handleWebsocket(EncoderHandler.java:211)
	at com.corundumstudio.socketio.handler.EncoderHandler.write(EncoderHandler.java:194)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:954)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:244)
	at com.corundumstudio.socketio.handler.ClientHead.sendPackets(ClientHead.java:148)
	at com.corundumstudio.socketio.handler.ClientHead.send(ClientHead.java:144)
	at com.corundumstudio.socketio.handler.PacketListener.onPacket(PacketListener.java:58)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:92)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:270)

**Comment by mrniko** [comment]
fixed

**Comment by pbondar** [comment]
[io.netty.channel.DefaultChannelPipeline.warn] [nioEventLoopGroup-3-6] [Failed to fail the promise because it's done already: DefaultChannelPromise@5725a222(success)]
java.lang.IllegalArgumentException: promise already done: DefaultChannelPromise@5725a222(success)
	at io.netty.channel.AbstractChannelHandlerContext.validatePromise(AbstractChannelHandlerContext.java:797) 
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:675) 
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:949) ~
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:249) ~
	at com.corundumstudio.socketio.handler.EncoderHandler.handleWebsocket(EncoderHandler.java:224)
	at com.corundumstudio.socketio.handler.EncoderHandler.write(EncoderHandler.java:194)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633) 
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32) 
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908) 
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960) 
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893) 
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) 
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) 
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) 
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)

**Comment by mrniko** [comment]
@pbondar fixed

**Comment by pbondar** [comment]
@mrniko ok now
