### ISSUE TITLE
Error during data processing.

### ISSUE THREAD

**Issue by pbondar** [mrniko/netty-socketio#303]
[ERROR] [] [com.corundumstudio.socketio.handler.InPacketHandler.channelRead0] [nioEventLoopGroup-3-6] [Error during data processing. Client sessionId: 9e0aa38e-637e-4594-a265-d9928382ca5c, data: 10:40/clipath]
java.lang.IllegalStateException: null
	at com.corundumstudio.socketio.protocol.PacketType.valueOfInner(PacketType.java:57) 
	at com.corundumstudio.socketio.protocol.PacketDecoder.readInnerType(PacketDecoder.java:94) 
	at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:174) 
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:144) 
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65) 
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36) 
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:270) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) 
	at com.corundumstudio.socketio.transport.PollingTransport.onPost(PollingTransport.java:161) 
	at com.corundumstudio.socketio.transport.PollingTransport.handleMessage(PollingTransport.java:120) 
	at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:97) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:132) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) 
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) 
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) 
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) 
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) 
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
which lib version do you use? I can't reproduce it with netty-socketio 1.7.8

**Comment by pbondar** [comment]
no problem with netty-socketio 1.7.8.
I'm reproduced  it on 1.7.9-SNAPSHOT(the last one from trunk).
But maybe problem with client version.

**Comment by mrniko** [comment]
Can't reproduce it with test like this on master branch:
```java
        PacketDecoder d = new PacketDecoder(null, null);
        ByteBuf buf = Unpooled.wrappedBuffer("10:40/clipath".getBytes());
        d.decodePackets(buf, null);
```

**Comment by pbondar** [comment]
yes, you are right, in test works ok.

Will check my server. Thanks for help.

**Comment by pbondar** [comment]
Hi,  problem exist when packet data like 'd=<something>', in my case 'd=10:40/clipath'
