### ISSUE TITLE
在测试环境没问题的代码在线上会报错，异常如下

### ISSUE THREAD

**Issue by fanfan0430** [mrniko/netty-socketio#333]
16:49:56.463 [nioEventLoopGroup-2-4] WARN  io.netty.channel.DefaultChannelPipeline 151 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:431)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:744)

**Comment by mrniko** [comment]
Please write in english

**Comment by wenerme** [comment]
He says 'It's ok in dev env, but in production env got bellow exception.'

@fanfan0430 Update to latest version and try again.

**Comment by chxiaowu** [comment]
@wenerme not fully understand the code in the annotation pacakge, would you like share something?

**Comment by wenerme** [comment]
Use the annotation to simplify the event handler

```
public class Example {
    public static void main(String[] args) throws InterruptedException {
        Configuration config = new Configuration();
        config.setHostname("0.0.0.0");
        config.setPort(9092);
        SocketConfig socketConfig = new SocketConfig();
        socketConfig.setReuseAddress(true);
        config.setSocketConfig(socketConfig);
        SocketIOServer server = new SocketIOServer(config);

        // add listener
        MyListeners handler = new MyListeners();
        server.addConnectListener(handler::onConnect);
        server.addDisconnectListener(handler::onDisconnect);
        server.addEventListener("chat", Map.class, handler::onData);

        // is same as
        server.addListeners(new MyHandlers());

        server.start();
    }

    public static class MyListeners implements ConnectListener, DisconnectListener, DataListener<Map<String, String>> {
        public void onConnect(SocketIOClient client) {
            // onConnect
        }

        @Override
        public void onDisconnect(SocketIOClient client) {
            // onDisconnect
        }

        @Override
        public void onData(SocketIOClient client, Map<String, String> data, AckRequest ackSender) throws Exception {
            // onData
        }
    }

    public static class MyHandlers {
        @OnConnect
        public void onConnect(SocketIOClient client) {
            // onConnect
        }

        @OnDisconnect
        public void onDisconnect(SocketIOClient client) {
            // onDisconnect
        }

        @OnEvent("chat")
        public void onData(SocketIOClient client, Map<String, String> data, AckRequest ackSender) throws Exception {
            // onData
        }
    }
}
``` 

Use annotation is way more easier.

**Comment by zyxzhsh** [comment]
在这说中文的话好多人看不懂

**Comment by devpage** [comment]
@zyxzhsh you can speak Chinese English

**Comment by wirechen** [comment]
@fanfan0430 请问你问题解决了吗？我也是差不读类似的问题，在本地测试环境没问题，部署到线上，浏览器客户端就连不上server

**Comment by lilaizhencn** [comment]
这个空指针异常其实是程序逻辑问题。不是框架自己报的异常。可以多打印一些log
