### ISSUE TITLE
Hello,the question about setUseLinuxNativeEpoll

### ISSUE THREAD

**Issue by jalion** [mrniko/netty-socketio#354]
throw the Exception when  I used setUseLinuxNativeEpoll

 [DEBUG] 2016-05-21 09:29:27 :-Dio.netty.eventLoopThreads: 2
 Exception in thread "Thread-5" java.lang.AbstractMethodError: io.netty.channel.MultithreadEventLoopGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/channel/EventLoop;
	at io.netty.channel.MultithreadEventLoopGroup.newChild(MultithreadEventLoopGroup.java:31)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:77)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:48)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:57)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:49)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41)
	at com.corundumstudio.socketio.SocketIOServer.initGroups(SocketIOServer.java:182)
	at com.corundumstudio.socketio.SocketIOServer.startAsync(SocketIOServer.java:131)
	at com.corundumstudio.socketio.SocketIOServer.start(SocketIOServer.java:123)

I have added   netty-transport-native-epoll dependency

**Comment by mrniko** [comment]
> java.lang.AbstractMethodError

Please check library versions

**Comment by jalion** [comment]
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-epoll</artifactId>
    <version>4.1.0.CR3</version>
    **_<classifier>linux-x86_64</classifier>_**
</dependency>

**Comment by jalion** [comment]
< dependency >
    < groupId>io.netty< /groupId >
    < artifactId >netty-transport-native-epoll</artifactId >
    < version>4.1.0.CR3< /version >
    < classifier>**linux-x86_64** < /classifier >
< /dependency >

I have solved the problem.
THANKS

**Comment by mrniko** [comment]
@jalion Good!
