### ISSUE TITLE
redission  cause  cpu  100%

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/netty-socketio#364]
redission   version  2.2.14    recursion cause Dead circulation
nioEventLoopGroup-2-2" prio=10 tid=0x00007fbd8818a000 nid=0xff7d runnable [0x00007fbd6c7f7000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.getStackTraceElement(Native Method)
        at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
        - locked <0x000000077a93a780> (a java.lang.Throwable)
        at java.lang.Throwable.getStackTrace(Throwable.java:816)
        at io.netty.util.ResourceLeakDetector.newRecord(ResourceLeakDetector.java:421)
        at io.netty.util.ResourceLeakDetector$DefaultResourceLeak.record0(ResourceLeakDetector.java:321)
        at io.netty.util.ResourceLeakDetector$DefaultResourceLeak.record(ResourceLeakDetector.java:311)
        at io.netty.buffer.AdvancedLeakAwareByteBuf.recordLeakNonRefCountingOperation(AdvancedLeakAwareByteBuf.java:59)
        at io.netty.buffer.AdvancedLeakAwareByteBuf.readByte(AdvancedLeakAwareByteBuf.java:399)
        at io.netty.handler.codec.ReplayingDecoderByteBuf.readByte(ReplayingDecoderByteBuf.java:517)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:210)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:283)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)

**Comment by mrniko** [comment]
Could you please update it to 2.2.16 version and switch log for `org.redisson` package to `trace` level?

**Comment by pengfei-xu** [comment]
I try  2.2.16 version  also Same phenomenon ; log level is trace  and most log is like
2016-06-20 15:58:15,640 DEBUG [pool-2-thread-1] com.corundumstudio.socketio.transport.NamespaceClient NamespaceClient.java:117 onDisconnect Client 777c11a7-d38c-4f76-ac67-74ad863f2bd6 for namespace  has been disconnected
2016-06-20 15:58:15,640 DEBUG [pool-2-thread-1] com.corundumstudio.socketio.handler.ClientHead ClientHead.java:129 run 777c11a7-d38c-4f76-ac67-74ad863f2bd6 removed due to ping timeout
2016-06-20 15:58:15,640 DEBUG [pool-2-thread-1] com.corundumstudio.socketio.transport.NamespaceClient NamespaceClient.java:117 onDisconnect Client 7fc6a787-01fa-4add-86b4-d91b2212938c for namespace /web_socket has been disconnected
2016-06-20 15:58:15,640 DEBUG [pool-2-thread-1] org.redisson.command.CommandAsyncService CommandAsyncService.java:603 checkConnectionFuture aquired connection for command (PUBLISH) and params [disconnect, com.corundumstudio.socketio.store.pubsub.DisconnectMessage@1134eebd] from slot NodeSource [slot=0, addr=null, redirect=null] using node /10.1.6.20:7091
2016-06-20 15:58:15,640 TRACE [nioEventLoopGroup-2-6] org.redisson.client.handler.CommandEncoder CommandEncoder.java:97 encode channel: [id: 0x2933ec1c, L:/10.1.5.114:7088 - R:/10.1.6.20:7091] message: *3^M
$7^M
PUBLISH^M
$10^M
disconnect^M
$170^M

**Comment by pengfei-xu** [comment]
![image](https://cloud.githubusercontent.com/assets/15759076/16187263/db0b63b8-3701-11e6-9247-a0ede5ab60e7.png)
tid 18650  cause Dead circulation

**Comment by a596620989** [comment]
could u please explain how to reproduce this issue?

**Comment by pengfei-xu** [comment]
I  use 6 client ;  each client use  websocket-bench -a 10000 -c 50  http://10.1.5.114:9003/web_socket  to pressure；

**Comment by mrniko** [comment]
I see logs from CommandEncoder only. Logs from org.redisson.client.handler.CommandDecoder should be too. This loop seems to be appear due-to incorrect bug in decoder. I need to know which command it tries to parse. That's why I'm asking for logs

**Comment by mrniko** [comment]
@pengfei-xu Could you provide logs from org.redisson.client.handler.CommandDecoder ? I need to understand which message format causes this issue

**Comment by pengfei-xu** [comment]
sorry, I can not reproduce it , cpu also high but  distribute average to each thread. I  will continue try it again. but now pressure cause another error , when i pressure it . ConnectionPool set 200 num 

![Uploading image.png…]()

**Comment by pengfei-xu** [comment]
sorry, I can not reproduce it , cpu also high but  distribute average to each thread. I  will continue try it again. but now pressure cause another error , when i pressure it . ConnectionPool set 200 num 

![Uploading image.png…]()

**Comment by pengfei-xu** [comment]
![image](https://cloud.githubusercontent.com/assets/15759076/16255642/423ca52e-387e-11e6-9815-048d8b5afe1f.png)

**Comment by pengfei-xu** [comment]
sorry, I can not reproduce it , cpu also high but distribute average to each thread. I will continue try it again. but now pressure cause another error , when i pressure it . ConnectionPool set 200 num

![image](https://cloud.githubusercontent.com/assets/15759076/16255642/423ca52e-387e-11e6-9815-048d8b5afe1f.png)

**Comment by mrniko** [comment]
Increase connection pool

**Comment by pengfei-xu** [comment]
help me see this . cpu also high but distribute average to each thread.   
The test box has four CPUs,, the output from 'top' is below: 
Cpu0  : 29.0%us, 21.7%sy,  0.0%ni,  8.3%id,  0.0%wa,  0.0%hi, 41.0%si,  0.0%st
Cpu1  : 32.0%us, 33.3%sy,  0.0%ni, 34.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  : 34.1%us, 33.1%sy,  0.0%ni, 32.8%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  : 35.0%us, 36.4%sy,  0.0%ni, 28.6%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   8059428k total,  6241052k used,  1818376k free,   270140k buffers
Swap:        0k total,        0k used,        0k free,  3533916k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
54911 jetty     20   0 7023m 1.8g  14m S 14.2 23.2   7:19.48 java
55430 jetty     20   0 7023m 1.8g  14m R 14.2 23.2   4:39.39 java
55553 jetty     20   0 7023m 1.8g  14m S 10.9 23.2   4:09.92 java
55557 jetty     20   0 7023m 1.8g  14m S 10.9 23.2   4:20.17 java
55551 jetty     20   0 7023m 1.8g  14m R 10.5 23.2   3:43.17 java
55552 jetty     20   0 7023m 1.8g  14m S 10.5 23.2   4:14.18 java
55554 jetty     20   0 7023m 1.8g  14m S 10.5 23.2   4:27.56 java
55549 jetty     20   0 7023m 1.8g  14m S 10.2 23.2   3:53.18 java
55563 jetty     20   0 7023m 1.8g  14m S 10.2 23.2   3:56.57 java
why the sy  proportion is so high. 
6 clients  to pressure
400 client onconect per second and disconnect after one minute , also send 4000 messages per second
hread Dump  most thread like is below: 
nioEventLoopGroup-2-2" prio=10 tid=0x00007f847a7e1800 nid=0xd67f runnable [0x00007f846c859000]
   java.lang.Thread.State: RUNNABLE
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:307)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:273)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:107)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:368)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:243)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1336)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:

**Comment by mrniko** [comment]
Could you please provide a test case or some test project to reproduce it?
