### ISSUE TITLE
Did anyone encountered CorruptedFrameException?

### ISSUE THREAD

**Issue by Kenvelo90** [mrniko/netty-socketio#374]
Using netty ssocketio 1.7.10 with the official java client and js client.
The netty framework throws CorruptedFrameException exceptions sporadically.
Any ideas?

Log:

2016-07-05 14:32:10 [nioEventLoopGroup-3-328] ERROR DefaultExceptionListener:48 - received a frame that is not masked as expected
io.netty.handler.codec.CorruptedFrameException: received a frame that is not masked as expected
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412) ~[netty-codec-http-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:193) ~[netty-codec-http-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) ~[netty-codec-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) ~[netty-codec-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.n

**Comment by aboutdata** [comment]
+1

**Comment by TheCycoONE** [comment]
+1

**Comment by pramodbms** [comment]
+1

**Comment by fcbflying** [comment]
Aren't there anyone explain more for this issue?

**Comment by CNQiYang** [comment]
i have the same problem. my client is io.socket:socket.io-client:0.8.3.
+1

**Comment by nkcoder** [comment]
same problem, any ideas?

		<dependency>
			<groupId>com.corundumstudio.socketio</groupId>
			<artifactId>netty-socketio</artifactId>
			<version>1.7.13</version>
		</dependency>

**Comment by czb1n** [comment]
sam problem in version 1.7.12

**Comment by lilaizhencn** [comment]
+1

**Comment by nantoniazzi** [comment]
+1

**Comment by sauravomar** [comment]
+1

**Comment by Bendor** [comment]
+1

**Comment by xuwuming** [comment]
+1
<dependency>
            <groupId>com.corundumstudio.socketio</groupId>
            <artifactId>netty-socketio</artifactId>
            <version>1.7.17</version>
        </dependency>
