### ISSUE TITLE
master version WrongUrlHandler

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/netty-socketio#384]
![image](https://cloud.githubusercontent.com/assets/15759076/17267757/7fb0e86e-5644-11e6-9c3f-b2bedb1074d2.png)

this code will release twice msg  cause it  @mrniko 
2016-07-29 01:31:35.961 WARN  c.c.s.handler.WrongUrlHandler.channelRead:52 Blocked wrong socket.io-context request! url: /jenkins/, params: {}, ip: /10.24.242.124:21818

2016-07-29 01:31:35.962 WARN  i.n.c.DefaultChannelPipeline.warn:151 An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:111) ~[netty-buffer-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.release(HttpObjectAggregator.java:316) ~[netty-codec-http-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84) ~[netty-common-4.1.1.Final.jar:4.1.1.Final]
        at com.corundumstudio.socketio.handler.WrongUrlHandler.channelRead(WrongUrlHandler.java:54) ~[netty-socketio-1.7.12-Final.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
        at com.corundumstudio.socketio.transport.WebSocketTransport.channelRead(WebSocketTransport.java:122) [netty-socketio-1.7.12-Final.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
        at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:110) [netty-socketio-1.7.12-Final.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]

**Comment by mrniko** [comment]
Fixed
