### ISSUE TITLE
certificate_unknown despite certificate being valid

### ISSUE THREAD

**Issue by oliverhausler** [mrniko/netty-socketio#398]
I am using the following setup sequence (this is a testserver, so you can try):

```
        // Configuration
        Configuration config = new Configuration();
        config.setHostname("https://octopus-176-9-157-236.attach.live");
        config.setPort(443);
        config.setExceptionListener(new LoggedExceptionListener());

        config.setKeyStorePassword(Keys.KEYSTORE_PASSWORD);
        InputStream stream = new KeystoreFile().getAsStream();
        config.setKeyStore(stream);

        config.setAckMode(AckMode.MANUAL);

        // Server
        socketIOServer = new SocketIOServer(config);
        socketIOServer.start();
```

When a client connects and also when I enter the root of the host in Chrome, I see this in the server log and it doesn't work:

```
Sep 02, 2016 12:09:40 AM live.attach.octopus.log.LoggedExceptionListener exceptionCaught
SEVERE: exceptionCaught
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:380)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1641)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1609)
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1775)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1064)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:888)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:762)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1138)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:349)
        ... 12 more
```

Everything works fine without TLS, and also, I have tried to set up a Jetty server on port 447 (accesses same certificate) and SSL works fine:

https://octopus-176-9-157-236.attach.live:447/ping

The certificate seems to be good, too:

https://www.ssllabs.com/ssltest/analyze.html?d=octopus-176-9-157-236.attach.live

Any ideas?

**Comment by oliverhausler** [comment]
The problem was that I did not have the intermediate certificate included in the keystore, and at the same time had a stupid client which did not resolve it on its own :( Solved, and not an issue here.
