### ISSUE TITLE
NotSslRecordException when closing browser tab

### ISSUE THREAD

**Issue by oliverhausler** [mrniko/netty-socketio#416]
When I have a browser tab connected to socket.io using TLS, an exception is thrown and the following stacktraces are logged:

```
2016-11-03 21:26:54,985 ERROR LoggedExceptionListener [nioEventLoopGroup-3-2] exceptionCaught
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 9880f5a41349d44e298884b76d2f528fafbe88d7334b506a73827e175cfded263cac14a0c80959619d226a40883757c403
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:915) [netty-handler-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-codec-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-common-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [netty-common-4.1.1.Final.jar:4.1.1.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
2016-11-03 21:26:54,987 ERROR com.corundumstudio.socketio.listener.DefaultExceptionListener [nioEventLoopGroup-3-2] not an SSL/TLS record: 9880f5a41349d44e298884b76d2f528fafbe88d7334b506a73827e175cfded263cac14a0c80959619d226a40883757c403
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 9880f5a41349d44e298884b76d2f528fafbe88d7334b506a73827e175cfded263cac14a0c80959619d226a40883757c403
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:915) [netty-handler-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-codec-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390) [netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-common-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [netty-common-4.1.1.Final.jar:4.1.1.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
```

This doesn't hurt, but we may want to suppress it, as we have an error in the log each time it happens.

**Comment by pablojr** [comment]
@oliverhausler I think that maybe it is not that bad to have this exception recorded as it signals that one of the parties in the SSL connection is sending a not encripted packet (from [Netty's documentation](https://netty.io/4.0/api/io/netty/handler/ssl/NotSslRecordException.html))
Have you traced the session (i.e. using Wireshark) just to check what the actual packet(s) are when the browser tab is closed?

**Comment by oliverhausler** [comment]
@pablojr I currently have no bandwidth for looking into this, but I will keep it on my list and update this issue later.

**Comment by pablojr** [comment]
@oliverhausler any updates on this issue? Were you able to verify the situation/proposed solution?
Please don't forget to close the ticket if applicable

**Comment by oliverhausler** [comment]
@pablojr I haven't been looking into this, but for completeness I pasted part of the log (Version 1.7.12):

```
javax.net.ssl.SSLHandshakeException: no cipher suites in common
javax.net.ssl.SSLHandshakeException: Client requested protocol SSLv3 not enabled or not supported
not an SSL/TLS record
Connection reset by peer
exceptionCaught
0624eb5f-fb3f-49f2-8fd0-1c30fb67428e is not registered. Closing connection
```
