### ISSUE TITLE
ClassNotFoundException com.fasterxml.jackson.annotation.JsonInclude 

### ISSUE THREAD

**Issue by SignalGo** [mrniko/netty-socketio#417]
how can i fix this error?
` public static void main(String[] args){
        configuration=getConfig(HOST_NAME,PORT);
        socketIOServer=new SocketIOServer(configuration);
        UserManager.getInstance(socketIOServer).run();

        socketIOServer.start();

    }`

Exception in thread "main" java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
	at com.corundumstudio.socketio.Configuration.<init>(Configuration.java:112)
	at com.corundumstudio.socketio.SocketIOServer.<init>(SocketIOServer.java:66)
	at Deer.main(Deer.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.corundumstudio.socketio.Configuration.<init>(Configuration.java:109)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude$Value
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:45)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:543)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:460)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport.<init>(JacksonJsonSupport.java:297)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport.<init>(JacksonJsonSupport.java:304)
	... 12 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonInclude$Value
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

**Comment by mrniko** [comment]
Please ensure that you have Jackson 2.7.x or above in your classpath.
