### ISSUE TITLE
Polling does not support chinese character

### ISSUE THREAD

**Issue by xiukongtiao** [mrniko/netty-socketio#434]
Hi,
When I run your demo after I upgrade the netty-socketio version from 1.7.7 to 1.7.12.
I found  if I send a English string like 'abc',  it works good.
But if I send a chinese word like '你好', there will be a exception:
[nioEventLoopGroup-3-8] ERROR com.corundumstudio.socketio.handler.InPacketHandler - Error during data processing. Client sessionId: 7610ac17-00dc-4d4e-848a-7da0bac5e3f1, data: :42["chatevent",{"userName":"user452","message":"你好"}]
java.lang.IllegalStateException
	at com.corundumstudio.socketio.protocol.UTF8CharsScanner.getActualLength(UTF8CharsScanner.java:108)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:137)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)

And I have checked the code, I foud this change looks like the reason,   can you help me to fonfirm it, thanks a alot!

![utf8pollingissuw](https://cloud.githubusercontent.com/assets/6489552/22861406/fc669f3a-f152-11e6-896e-f43bf9ee7730.png)

**Comment by devpage** [comment]
@xiukongtiao  IE7 下 你用的哪个websocket库

**Comment by swit1983** [comment]
@devpage 我这边是服务端版本1.7.12    客户端用的socket.io-client-swift v9   会出现这个异常。js客户不会
