### ISSUE TITLE
json parse error

### ISSUE THREAD

**Issue by huazi221** [mrniko/netty-socketio#447]
2017-03-31 17:35:48,268 ERROR [com.corundumstudio.socketio.JsonSupportWrapper] - Can't read value: ["create_order","{\"to\":\"aaa\",\"from\":\"bbb\",\"orderNo\":\"ccc\"}"] for type: class com.corundumstudio.socketio.protocol.Event
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class message.OrderMessage] from String value ('{"to":"shouyinji","from":"fuwsheng2","orderNo":"jhhhh"}'); no single-String constructor/factory method
 at [Source: io.netty.buffer.ByteBufInputStream@b6b034c; line: 1, column: 17]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:992)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:316)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1200)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:144)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3779)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2050)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport$EventDeserializer.deserialize(JacksonJsonSupport.java:194)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport$EventDeserializer.deserialize(JacksonJsonSupport.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at com.corundumstudio.socketio.protocol.JacksonJsonSupport.readValue(JacksonJsonSupport.java:340)
	at com.corundumstudio.socketio.JsonSupportWrapper.readValue(JsonSupportWrapper.java:54)
	at com.corundumstudio.socketio.protocol.PacketDecoder.parseBody(PacketDecoder.java:304)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:181)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:147)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)

**Comment by jingzhongyue** [comment]
https://github.com/mrniko/netty-socketio/issues/258#issuecomment-465497609
