### ISSUE TITLE
IndexOutOfBoundsException when using byte[] and multiple connections

### ISSUE THREAD

**Issue by philippproegel** [mrniko/netty-socketio#455]
My tech-Stack: 
Server-> netty-socketio,msgpack      Client-> socket.io-client in javascript,msgpack

The following error occurs when using binary data =>
addEventListener(eventName, byte[].class, new DataListener<byte[]>())
and multiple client connections.

If i switch to json for serialization and expect String data on serverside =>addEventListener(eventName, String.class, new DataListener<String>()
the error doesnt occur.

nioEventLoopGroup-3-8] WARN io.netty.channel.AbstractChannelHandlerContext - Failed to fail the promise because it's done already: DefaultChannelPromise@13d544e4(success)
java.lang.IndexOutOfBoundsException: readerIndex: 300 (expected: 0 <= readerIndex <= writerIndex(150))
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:103)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1061)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1050)
	at com.corundumstudio.socketio.handler.EncoderHandler.handleWebsocket(EncoderHandler.java:256)
	at com.corundumstudio.socketio.handler.EncoderHandler.write(EncoderHandler.java:211)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1101)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1148)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1090)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pablojr** [comment]
Has your workaround worked fine for you? Could it be possible you provide a patch for review? so the potential fix could be applied upstream if it's Ok

Thanks.
