### ISSUE TITLE
in version 1.7.13. the netty jar which version is 4.1.5.Final with jar conflict question

### ISSUE THREAD

**Issue by liuliliGithub** [mrniko/netty-socketio#492]
hi, i use netty-socketio 1.7.13 version. when i run my code, then with exception like :
```java
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at io.netty.channel.ChannelOutboundBuffer.<clinit>(ChannelOutboundBuffer.java:92)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:421)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:218)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:58)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:58)
```
then i see netty-socketio use netty-transport-4.1.5.Final.jar. 
```java
        AtomicIntegerFieldUpdater<ChannelOutboundBuffer> unwritableUpdater =
                PlatformDependent.newAtomicIntegerFieldUpdater(ChannelOutboundBuffer.class, "unwritable");
```
the class - PlatformDependent no method like newAtomicIntegerFieldUpdater.
please modify your dependency.

**Comment by JonGDropbox** [comment]
FWIW, it appears that the version was updated a few months ago but not released to mvn:
https://github.com/mrniko/netty-socketio/commit/22d651b3dd71b72d27c2e295db4b87d3dbb58ea2#diff-600376dffeb79835ede4a0b285078036

(The mvn netty-socketio/1.7.13 dependency on netty-transport/4.1.5.Final is incompatible with its dependency on netty-common/4.1.15 that drops those PlatformDependent methods.)

**Comment by liuliliGithub** [comment]
yes，i know they are incompatible.I lowered the version number to 4.1.15.
