### ISSUE TITLE
Cannot assign requested address in AWS

### ISSUE THREAD

**Issue by DaniAkash** [mrniko/netty-socketio#493]
I have implemented a websocket server using Spring framework and Netty SocketIO. While development I used the host address as `localhost` and the server was working perfectly fine.

When I'm trying to deploy my code to AWS, I changed the host address to my instance's public IP address. But I'm getting the following error and I'm unable to start my server

```
Caused by: java.net.BindException: Can't assign requested address
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:484)
at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1080)
at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:197)
at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:350)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
```

**Comment by DaniAkash** [comment]
Should I be using any other IP address instead of the public IP address of my Instance?

**Comment by sunilgulabani** [comment]
@DaniAkash Am facing same issue. Did you found any solution?

**Comment by lilaizhencn** [comment]
ifconfig find  intranet ip, use it

**Comment by pablojr** [comment]
@DaniAkash @sunilgulabani if you ever solved this issue in AWS with suggestion from @lilaizhencn please don't forget to update this ticket so we can document a "AWS How-to" later. Thanks.

**Comment by sunilgulabani** [comment]
@pablojr I was able to resolve this issue. When we create SocketIO Server with hostname as "localhost", application is only accessible from local environment. I changed the hostname parameter value to "0.0.0.0" and it worked seamlessly. Rest AWS security group need to be expose for port which we used.

**Comment by DaniAkash** [comment]
@sunilgulabani it works! thank you!!

**Comment by anilpawar1** [comment]
thanks bro..

**Comment by hbtechnologia** [comment]
> @pablojr I was able to resolve this issue. When we create SocketIO Server with hostname as "localhost", application is only accessible from local environment. I changed the hostname parameter value to "0.0.0.0" and it worked seamlessly. Rest AWS security group need to be expose for port which we used.

can you please tell me how to do that i am facing same issue but do not know how to do that. ??Your help wil be appreciated with bundle of thanks.
![ss](https://user-images.githubusercontent.com/56894126/70751941-690a5f80-1d53-11ea-944c-031a3bc27142.PNG)

**Comment by hbtechnologia** [comment]
> @sunilgulabani it works! thank you!!

can you please tell me how to do that i am facing same issue but do not know how to do that. ??Your quick help will be highly appreciated...
