### ISSUE TITLE
NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;

### ISSUE THREAD

**Issue by niko2014** [mrniko/netty-socketio#496]
# env

I ran `ChatLauncher` in [mrniko/netty-socketio-dem](https://github.com/mrniko/netty-socketio-demo/blob/master/server/src/main/java/com/corundumstudio/socketio/demo/ChatLauncher.java) with `netty-socketio:1.7.13` , while it failed to start server.

# error log 

```f
[main] INFO com.corundumstudio.socketio.SocketIOServer - Session store / pubsub factory used: MemoryStoreFactory (local session store only)
Exception in thread "main" io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
	at com.corundumstudio.socketio.SocketIOServer.startAsync(SocketIOServer.java:151)
	at com.corundumstudio.socketio.SocketIOServer.start(SocketIOServer.java:123)
	at com.corundumstudio.socketio.demo.ChatLauncher.main(ChatLauncher.java:38)
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at io.netty.channel.ChannelOutboundBuffer.<clinit>(ChannelOutboundBuffer.java:92)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:421)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:218)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:58)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:58)
	at io.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:47)
	at io.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:35)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:80)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 6 more
```

**Comment by jotgugu** [comment]
me too...

**Comment by lvjinchengcq** [comment]
me too
the dependency version do not have the function any more
  dependency
  	groupId io.netty
  	artifactId netty-transport
       version 4.1.5.Final
  dependency

**Comment by jinny76** [comment]
Same issue when upgrading from 1.7.12 to 1.7.13

**Comment by lilaizhencn** [comment]
package eroor @jinny76

**Comment by nickevin** [comment]
Try this way, @jinny76 :

```
<dependency>
    <groupId>com.corundumstudio.socketio</groupId>
    <artifactId>netty-socketio</artifactId>
    <version>1.7.13</version>
</dependency>
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport</artifactId>
    <version>4.1.15.Final</version>
</dependency>
```

**Comment by oryjk** [comment]
I add 
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport</artifactId>
    <version>4.1.15.Final</version>
</dependency>
it is work!
but a warning occur:Found Netty's native epoll transport in the classpath, but epoll is not available. Using NIO instead.
then I add 
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-transport-native-epoll</artifactId>
	<version>4.1.15.Final</version>
	<classifier>linux-x86_64</classifier>
</dependency>
that work ok

**Comment by jellythefish** [comment]
Seems like this error is connected with invalid async-http-client version.
In my case this answer helped: https://github.com/kamon-io/kamon-influxdb/issues/11#issuecomment-326270128
Try to fix it with:
```
<dependency>
	<groupId>org.asynchttpclient</groupId>
	<artifactId>async-http-client</artifactId>
	<version>2.0.35</version>
</dependency>
```
