### ISSUE TITLE
 Application startup failed - java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by leohsu91** [mrniko/netty-socketio#500]
Hi, I Iintegrated this project with springboot，It works fine on my computer but started failed in a docker environment.
Here is the code
`@Component
public class MySocketIoServer {

    Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    private MyAuthorizationListener myAuthorizationListener;

    @Bean
    public SocketIOServer socketIOServer(MyNettyConfig myNettyConfig) {
        myNettyConfig.setAuthorizationListener(myAuthorizationListener);
        final SocketIOServer server = new SocketIOServer(myNettyConfig);
        return server;
    }
}`

`@Component
public class NettyServerLauncher implements CommandLineRunner {

    Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    private MyConnetionListener myConnetionListener;

    @Autowired
    private MyDisConnetionListener myDisConnetionListener;

    @Autowired
    private SocketIOServer server;

    @Override
    public void run(String... strings) throws Exception {

        logger.info("start netty socket server...");

        server.addConnectListener(myConnetionListener);
        server.addDisconnectListener(myDisConnetionListener);

        server.start();

        logger.info("start netty socket server success!");

        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                server.stop();
                logger.info("close netty socket server.");
            }
        });

    }
}
`

Error:
`18:58:33.622 [main] ERROR o.s.b.SpringApplication - Application startup failed
java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concu
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
        at com.corundumstudio.socketio.SocketIOServer.initGroups(SocketIOServer.java:184)
        at com.corundumstudio.socketio.SocketIOServer.startAsync(SocketIOServer.java:130)
        at com.corundumstudio.socketio.SocketIOServer.start(SocketIOServer.java:122)
        at com.netease.pbim.push.NettyServerLauncher.run(NettyServerLauncher.java:37)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at com.netease.pbim.push.PushApplication.main(PushApplication.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)`

**Comment by leohsu91** [comment]
fixed when upgrated to 1.7.13 
` <dependency>
            <groupId>com.corundumstudio.socketio</groupId>
            <artifactId>netty-socketio</artifactId>
            <version>1.7.13</version>
        </dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-transport</artifactId>
			<version>4.1.15.Final</version>
		</dependency>`
