### ISSUE TITLE
set UserLinuxNativeEpoll is true error :Method io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errnoENOENT()I not found

### ISSUE THREAD

**Issue by lilaizhencn** [mrniko/netty-socketio#509]
in my project,
i set configure 
```
Configuration config = new Configuration();
  config.setUseLinuxNativeEpoll(true);
```
and  in pom.xml
```
 <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.17.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
```

then package to jar  ,running on centos,

```
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:55) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-common-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-common-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-common-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:52) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at com.corundumstudio.socketio.SocketIOServer.initGroups(SocketIOServer.java:179) ~[netty-socketio-1.7.14.i-SNAPSHOT.jar!/:na]
        at com.corundumstudio.socketio.SocketIOServer.startAsync(SocketIOServer.java:131) ~[netty-socketio-1.7.14.i-SNAPSHOT.jar!/:na]
        at com.corundumstudio.socketio.SocketIOServer.start(SocketIOServer.java:123) ~[netty-socketio-1.7.14.i-SNAPSHOT.jar!/:na]
        at com.xyhj.chaoex.quote.QuoteListener.onApplicationEvent(QuoteListener.java:37) ~[classes!/:na]
        at com.xyhj.chaoex.quote.QuoteListener.onApplicationEvent(QuoteListener.java:20) ~[classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:353) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:100) ~[spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79) ~[spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72) ~[spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:329) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M7.jar!/:2.0.0.M7]
        at com.xyhj.chaoex.QuoteProcessApplication.main(QuoteProcessApplication.java:18) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [quote-process-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [quote-process-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [quote-process-0.0.1-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [quote-process-0.0.1-SNAPSHOT.jar:na]
Caused by: java.lang.NoSuchMethodError: Method io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errnoENOENT()I not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[na:1.8.0_131]
        at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_131]
        at java.lang.System.load(System.java:1086) ~[na:1.8.0_131]
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36) ~[netty-common-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243) ~[netty-common-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:187) ~[netty-common-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:207) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.Native.<clinit>(Native.java:65) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33) ~[netty-transport-native-epoll-4.1.17.Final.jar!/:4.1.17.Final]
        ... 36 common frames omitted
```

**Comment by waterforce1205** [comment]
I have the same issue. Have you had any solution yet?

**Comment by lilaizhencn** [comment]
add netty-all pom to fix

**Comment by waterforce1205** [comment]
Awesome, work likes charm. Thank you so much!
