### ISSUE TITLE
.Net客户端可以连接接受数据 但是无法发送

### ISSUE THREAD

**Issue by EastFive** [mrniko/netty-socketio#534]
偶尔能连接认证成功，但更多的是报错。
客户端是这个https://github.com/Quobject/SocketIoClientDotNet/

错误信息如下：
2018-04-03 17:29:23.824 ERROR 4484 --- [ntLoopGroup-3-3] c.c.socketio.handler.InPacketHandler     : Error during data processing. Client sessionId: 3c65e6f5-9b51-4238-84a0-0e298e1cdf9b, data: ?42[
  "authentication",
  "{\"clientCode\":\"CN-DALIAN-DCTRT-QC01\",\"clientName\":\"QC14-??01\"}"
]

java.lang.IndexOutOfBoundsException: UnpooledHeapByteBuf(ridx: 4, widx: 108, cap: 108/108).slice(5, 107)
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.checkSliceOutOfBounds(AbstractUnpooledSlicedByteBuf.java:494)
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.<init>(AbstractUnpooledSlicedByteBuf.java:39)
	at io.netty.buffer.UnpooledSlicedByteBuf.<init>(UnpooledSlicedByteBuf.java:25)
	at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:1188)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:129)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at com.corundumstudio.socketio.transport.PollingTransport.onPost(PollingTransport.java:162)
	at com.corundumstudio.socketio.transport.PollingTransport.handleMessage(PollingTransport.java:121)
	at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:134)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by EastFive** [comment]
也会开始频繁的重连 
大概三秒后就断了
2018-04-03 17:34:17.762  WARN 4484 --- [ntLoopGroup-3-7] socketio.service.ConnectModuleService    : disConnect|handler|1f3be123-0812-43ef-9288-7efb4bf7d220
2018-04-03 17:34:17.762  WARN 4484 --- [ntLoopGroup-3-8] socketio.service.ConnectModuleService    : disConnect|handler|e68c90e9-91ed-411e-8f56-f794835525cd
2018-04-03 17:34:17.762  WARN 4484 --- [ntLoopGroup-3-7] socketio.service.ConnectModuleService    : disPoollisten|handel|1f3be123-0812-43ef-9288-7efb4bf7d220
2018-04-03 17:34:17.773  WARN 4484 --- [ntLoopGroup-3-8] socketio.service.ConnectModuleService    : disPoollisten|handel|e68c90e9-91ed-411e-8f56-f794835525cd
2018-04-03 17:34:33.559  WARN 4484 --- [pool-3-thread-1] socketio.service.ConnectModuleService    : disConnect|handler|26d4ff99-fa20-4710-bade-15c8ab1e9968
2018-04-03 17:34:33.560  WARN 4484 --- [pool-3-thread-1] socketio.service.ConnectModuleService    : disPoollisten|handel|26d4ff99-fa20-4710-bade-15c8ab1e9968
2018-04-03 17:34:33.561  WARN 4484 --- [pool-3-thread-1] socketio.service.ConnectModuleService    : disConnect|handler|15a7834b-2145-499f-8d0a-744c3604ad4a
2018-04-03 17:34:33.590  WARN 4484 --- [pool-3-thread-1] socketio.service.ConnectModuleService    : disPoollisten|handel|15a7834b-2145-499f-8d0a-744c3604ad4a
2018-04-03 17:34:44.659  WARN 4484 --- [pool-3-thread-1] socketio.service.ConnectModuleService    : disConnect|handler|a79acf2f-a1c5-4c71-9fd9-a2ba089f97c7
2018-04-03 17:34:44.672  WARN 4484 --- [pool-3-thread-1] socketio.service.ConnectModuleService    : disPoollisten|handel|a79acf2f-a1c5-4c71-9fd9-a2ba089f97c7

**Comment by nybbs2003** [comment]
@mrniko .NET client can connect and receive data,but fail to send.

**Comment by EastFive** [comment]
Use ws:ip:port to connect  fixed this quest
