### ISSUE TITLE
new update destroys socketio

### ISSUE THREAD

**Issue by Justin99b** [mrniko/netty-socketio#556]
You know i was programming my website and used (LATEST) in maven so ..... all of the sudden my connection just dont work anymore then AFTER 5 HOURS i saw YOU UPDATED and destroyed the connection i dont know why... but... its just not working anymore here are some screenshots 
Client: http://prntscr.com/jir61e
Server: http://prntscr.com/jir676

serusly i was so freaking frustrated and raged after i found out its because you failed the newes version.

Serusly its not working on the newest version 

PRO TIP: NEVER USE {LATEST} IN MAVEN

Please give me any advice how to my my "connect event is not even fireing" problem an also in chrome it says pending for more than a minute and then i get an error in java

maby its helping you to fix the issue http://prntscr.com/jir78a

**Comment by hymmyh** [comment]
我这边也出现同样的问题. 1.7.15 不能用呀
: receive connect event by 3830e82e-19dd-46c1-bb3f-f5a89cbc38c2, POLLING
2018-05-17 16:56:46.393  WARN 21333 --- [ntLoopGroup-3-2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.lang.NullPointerException: null
	at com.corundumstudio.socketio.transport.WebSocketTransport.channelInactive(WebSocketTransport.java:151) ~[netty-socketio-1.7.15.jar!/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]

**Comment by mrniko** [comment]
Fixed

**Comment by patrickgombert** [comment]
@mrniko would you mind cutting a new release with this change?

**Comment by Justin99b** [comment]
Its not fixed :<

**Comment by anhlt309** [comment]
@mrniko How can I get version  1.7.16 to fix this bug? Thank you!
