### ISSUE TITLE
receive emoji exception

### ISSUE THREAD

**Issue by hymmyh** [mrniko/netty-socketio#559]
![image](https://user-images.githubusercontent.com/580395/40339608-cad220de-5dad-11e8-91d9-a73ad67f9972.png)

java.lang.IndexOutOfBoundsException: UnpooledHeapByteBuf(ridx: 3, widx: 133, cap: 133/133).slice(4, 130)
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.checkSliceOutOfBounds(AbstractUnpooledSlicedByteBuf.java:474) ~[netty-buffer-4.1.25.Final.jar!/:4.1.25.Final]
	at io.netty.buffer.AbstractUnpooledSlicedByteBuf.<init>(AbstractUnpooledSlicedByteBuf.java:38) ~[netty-buffer-4.1.25.Final.jar!/:4.1.25.Final]
	at io.netty.buffer.UnpooledSlicedByteBuf.<init>(UnpooledSlicedByteBuf.java:24) ~[netty-buffer-4.1.25.Final.jar!/:4.1.25.Final]
	at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:1197) ~[netty-buffer-4.1.25.Final.jar!/:4.1.25.Final]
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:143) ~[netty-socketio-1.7.16.1-SNAPSHOT.jar!/:na]
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65) [netty-socketio-1.7.16.1-SNAPSHOT.jar!/:na]
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36) [netty-socketio-1.7.16.1-SNAPSHOT.jar!/:na]

**Comment by plainheart** [comment]
@hymmyh  I think it will work if you send emoji data encoded with Base64 but not original data.
