### ISSUE TITLE
OutOfDirectMemoryError

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/netty-socketio#578]
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1056964615, max: 1073741824)
full gc  can not  release  out of heap memory !

**Comment by hangsucho** [comment]
What is the Xms and Xmx value of the Java vm option?

It is recommended to increase the heap size.

**Comment by pengfei-xu** [comment]
@hangsucho  -Xmx3444m -Xms3444m -Xmn1968m -Xss256k -XX:MaxDirectMemorySize=1024m
when  I  increase the heap size  XX:MaxDirectMemorySize=2048  it donot trigger full gc but use 
 heap size with 7G greater than Xmx+MaxDirectMemorySize, and than cause oom 
https://github.com/mrniko/netty-socketio/issues/581

**Comment by hangsucho** [comment]
Are you using the latest version?

**Comment by pengfei-xu** [comment]
@hangsucho 嗯 i use master version  when I close HttpContentCompressor and WebSocketServerCompressionHandler  solve this question

**Comment by mrniko** [comment]
@pengfei-xu 

What do you mean "close"? Could you provide more details about your approach?

**Comment by pengfei-xu** [comment]
2018-07-23 17:32:16 0ms [nioEventLoopGroup-5-3] com.corundumstudio.socketio.protocol.PacketEncoder@11407e45 com/corundumstudio/socketio/protocol/PacketEncoder.encodePacket [Packet [type=MESSAGE, ackId=null] AdvancedLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 13, cap: 256)) PooledByteBufAllocator(directByDefault: true) true] void
2018-07-23 17:32:16 0ms [nioEventLoopGroup-5-1] com.corundumstudio.socketio.protocol.PacketEncoder@11407e45 com/corundumstudio/socketio/protocol/PacketEncoder.encodePacket [Packet [type=MESSAGE, ackId=null] AdvancedLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 1, cap: 256)) PooledByteBufAllocator(directByDefault: true) true] java.lang.NullPointerException
	at com.corundumstudio.socketio.protocol.PacketEncoder.encodePacket(PacketEncoder.java:287)
	at com.corundumstudio.socketio.handler.EncoderHandler.handleWebsocket(EncoderHandler.java:225)
	at com.corundumstudio.socketio.handler.EncoderHandler.write(EncoderHandler.java:199)
@hangsucho

**Comment by pengfei-xu** [comment]
![image](https://user-images.githubusercontent.com/15759076/43071162-79286f4a-8ea4-11e8-8e85-ae148d84c1e5.png)
this do not set subType
@dzn@hangsucho

**Comment by lizu18xz** [comment]
Has this problem been solved?

**Comment by lizu18xz** [comment]
Packet packet = new Packet(PacketType.MESSAGE);   



@mrniko @robymus  @alim-akbashev  @whg333 @ntrp 
Has this problem been solved? 

Null pointer exception is reported.
when 
byte subType = toChar(packet.getSubType().getValue());
buf.writeByte(subType);
