### ISSUE TITLE
Is it possible to use netty-socketio with spring mvc?

### ISSUE THREAD

**Issue by 0M1N0U5** [mrniko/netty-socketio#586]
Anybody knows if spring mvc version 5.0.7.RELEASE is working with netty-socketio version 1.7.16? Reading the dependencies I see that different versions are used in the com.fasterxml.jackson library:

Spring mvc -> 2.9.5
Netty-SocketIO  -> 2.7.9

When I start my server it throws me the following exception:

> java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1928)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1771)
> 	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:74)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.<init>(RequestMappingHandlerAdapter.java:188)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1230)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1137)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
> 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:672)
> 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:638)
> 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:686)
> 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:554)
> 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:499)
> 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:172)
> 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
> 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
> 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
> 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
> 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5409)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5707)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1702)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1692)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Is it possible to use netty-socketIO with the latest version of Spring MVC?

In case it is not possible. What is the maximum version of Spring MVC that I can use along with the latest version of netty-socketIO ?

Thank you

**Comment by 0M1N0U5** [comment]
I have got a configuration that allows to start the server. Modify your pom.xml file, exclude the netty-socketio libraries and add the same version you need for spring mvc separately.

> [...]
> <properties>
> 		<java-version>1.8</java-version>
> 		
> 		<org.springframework-version>5.0.7.RELEASE</org.springframework-version>
> 		<org.aspectj-version>1.9.1</org.aspectj-version>
> 		<org.slf4j-version>1.7.25</org.slf4j-version>
> 	</properties>
> 	<dependencies>
> 		
> 		<dependency>
> 			<groupId>org.springframework</groupId>
> 			<artifactId>spring-context</artifactId>
> 			<version>${org.springframework-version}</version>
> 			<exclusions>
> 				
> 				<exclusion>
> 					<groupId>commons-logging</groupId>
> 					<artifactId>commons-logging</artifactId>
> 				 </exclusion>
> 			</exclusions>
> 		</dependency>
> 		
> 		<dependency>
> 			<groupId>org.springframework</groupId>
> 			<artifactId>spring-webmvc</artifactId>
> 			<version>${org.springframework-version}</version>
> 		</dependency>
> 		
> 		<dependency>
> 		    <groupId>com.corundumstudio.socketio</groupId>
> 		    <artifactId>netty-socketio</artifactId>
> 		    <version>1.7.16</version>
> 		    <exclusions>
> 				<exclusion>
> 					<groupId>com.fasterxml.jackson.core</groupId>
> 					<artifactId>jackson-core</artifactId>
> 				</exclusion>
> 				<exclusion>
> 					<groupId>com.fasterxml.jackson.core</groupId>
> 					<artifactId>jackson-databind</artifactId>
> 				</exclusion>
> 			</exclusions>		
> 		</dependency>
> 		
> 		
> 		<dependency>
> 		    <groupId>com.fasterxml.jackson.core</groupId>
> 		    <artifactId>jackson-databind</artifactId>
> 		    <version>2.9.5</version>
> 		</dependency>
> 		
> 		<dependency>
> 		    <groupId>com.fasterxml.jackson.core</groupId>
> 		    <artifactId>jackson-core</artifactId>
> 		    <version>2.9.5</version>
> 		</dependency>
> [...]

Even so, I have not tested this configuration. Later I will put if it works correctly or not.

Regards.
