### ISSUE TITLE
use Redisson 3.8.0 error

### ISSUE THREAD

**Issue by kevinsui581** [mrniko/netty-socketio#602]
I use redisson 3.8.0 create RedissonStoreFactory, when client connect server, i got error:
Exception in thread "redisson-3-7" java.lang.AbstractMethodError: com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(Ljava/lang/CharSequence;Ljava/lang/Object;)V
	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:77)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:77)
	at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:181)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kevinsui581** [comment]
but use redisson 2.12.0, everything is ok!

**Comment by mrniko** [comment]
Fixed! Thanks for report
