### ISSUE TITLE
 create a cluster of netty socketio servers error

### ISSUE THREAD

**Issue by TalkIsCheapGiveMeMoney** [mrniko/netty-socketio#616]
// Instantiate Redisson configuration
Config redissonConfig = new Config();
redissonConfig.useSingleServer().setAddress("127.0.0.1:6379");
 
// Instantiate Redisson connection
RedissonClient redisson = Redisson.create(redissonConfig);
 
// Instantiate RedissonClientStoreFactory
RedissonStoreFactory redisStoreFactory = new RedissonStoreFactory(redisson);
 
// Instantiate SocketIO Configuration
Configuration config = new Configuration();
config.setHostname("localhost");
config.setPort(9092);
config.setStoreFactory(redisStoreFactory);
 
// Instantiate SocketIO Server
SocketIOServer server = new SocketIOServer(config);

使用redisson 3.7.5 redis 3.0.0 报错

Exception in thread "redisson-3-5" java.lang.NullPointerException
	at com.corundumstudio.socketio.store.pubsub.BaseStoreFactory$5.onMessage(BaseStoreFactory.java:79)
	at com.corundumstudio.socketio.store.pubsub.BaseStoreFactory$5.onMessage(BaseStoreFactory.java:74)
	at com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(RedissonPubSubStore.java:61)
	at com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(RedissonPubSubStore.java:57)
	at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:76)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:81)
	at org.redisson.client.handler.CommandPubSubDecoder$2.run(CommandPubSubDecoder.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cowKnight** [comment]
you should write 'redis:127.0.0.1:6379'
