### ISSUE TITLE
transport websocket error java.lang.IllegalStateException: null

### ISSUE THREAD

**Issue by hawind** [mrniko/netty-socketio#650]
```
var socket = io('http://localhost:9092/chat?token=abc123', {
 transports: ['websocket', 'polling']
 });
```

这里将websocket放在前面连接的时候报错，不管是连接还是断开都报错。
socket.io-client在高版本比如2x，测试了1x依然也是这个错，为了适配小程序版本，也必须使用2x才行

```
2019-03-02 03:59:05.244 DEBUG 4508 --- [ntLoopGroup-3-1] c.j.s.r.modules.chat.ChatModule          : Client[6be046ec-6f91-4f9d-b60d-e95c2c2f95f8] - Connected to chat module through '/socket.io/?token=abc123&EIO=3&transport=websocket'
2019-03-02 03:59:05.274 ERROR 4508 --- [ntLoopGroup-3-1] c.c.socketio.handler.InPacketHandler     : Error during data processing. Client sessionId: 6be046ec-6f91-4f9d-b60d-e95c2c2f95f8, data: token=abc123,

java.lang.IllegalStateException: null
	at com.corundumstudio.socketio.protocol.PacketType.valueOf(PacketType.java:48) ~[netty-socketio-1.7.17.jar:na]
	at com.corundumstudio.socketio.protocol.PacketDecoder.readType(PacketDecoder.java:86) ~[netty-socketio-1.7.17.jar:na]
	at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:160) ~[netty-socketio-1.7.17.jar:na]
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:142) ~[netty-socketio-1.7.17.jar:na]
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65) [netty-socketio-1.7.17.jar:na]
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36) [netty-socketio-1.7.17.jar:na]
```

**Comment by hawind** [comment]
发现问题了，只要添加了namespace在socket.io-client 2x里面就会出错...

**Comment by slyang520** [comment]
@hawind   https://github.com/slyang520/SocketIOServer  我这里正常啊

**Comment by liaopengju** [comment]
Hello, has the problem been solved?

**Comment by hawind** [comment]
已经弃坑，换golang了

**Comment by shibd** [comment]
从新打开这个issue吧，这个问题有人解决吗？

**Comment by penzhang** [comment]
Is there any solution for this issue??

**Comment by FuYouJ** [comment]
怎么还没解决
