### ISSUE TITLE
In 1.7.14 and later, multiple pages are opened in the same browser, and only the latest client can receive messages.

### ISSUE THREAD

**Issue by xiaochenggui** [mrniko/netty-socketio#657]
In 1.7.14 and later, multiple pages are opened in the same browser, and only the latest client can receive messages.

**Comment by Maypeur** [comment]
Same thing here, moreover, each tab seams to disconnect/reconnect with the following trace :
18/03/2019 08:45:44.918 @exceptionCaught : Connexion ré-initialisée par le correspondant
java.io.IOException: Connexion ré-initialisée par le correspondant
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ellavas** [comment]
Maybe related with the issue I have on 1.7.17. 
getAllClients contains only one client.
