### ISSUE TITLE
PacketType.valueOf throws IllegalStateException

### ISSUE THREAD

**Issue by MatCuk** [mrniko/netty-socketio#706]
Hi,

I'm using socket.io server 1.7.17.
I'm connecting to a namespace /profile-0 from Chrome using 

> "socket.io-client": "2.0.3"

Client connects normally. When he sends first message to login I see on server this error:

> 2019-09-06 10:28:47,673 [nioEventLoopGroup-3-1] [ERROR] [c.c.s.handler.InPacketHandler] - Error during data processing. Client sessionId: e79dfa62-a088-4e52-b019-0612656df755, data: 
java.lang.IllegalStateException: null
	at com.corundumstudio.socketio.protocol.PacketType.valueOf(PacketType.java:48)
	at com.corundumstudio.socketio.protocol.PacketDecoder.readType(PacketDecoder.java:86)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:160)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:142)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java

> 

I see PacketType supported are 
` OPEN(0), CLOSE(1), PING(2), PONG(3), MESSAGE(4), UPGRADE(5), NOOP(6),

    CONNECT(0, true), DISCONNECT(1, true), EVENT(2, true), ACK(3, true), ERROR(4, true), BINARY_EVENT(5, true), BINARY_ACK(6, true);`

But type received is 12.
https://i.imgur.com/Q08Vrbn.png

Here is whole msg flow:
https://i.imgur.com/Dfc99YX.png

**Comment by MatCuk** [comment]
Also I want to disallow default namespace "".
If I do socketIOServer.removeNamespace(""); I get:

>  An exception was thrown by com.corundumstudio.socketio.transport.WebSocketTransport$1.operationComplete()
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.contains(ConcurrentHashMap.java:4558)
	at com.corundumstudio.socketio.handler.AuthorizeHandler.connect(AuthorizeHandler.java:255)
	at com.corundumstudio.socketio.transport.WebSocketTransport.connectClient(WebSocketTransport.java:195)
	at com.corundumstudio.socketio.transport.WebSocketTransport.access$200(WebSocketTransport.java:57)
	at com.corundumstudio.socketio.transport.WebSocketTransport$1.operationComplete(WebSocketTransport.java:176)

because
`  Namespace ns = namespacesHub.get(Namespace.DEFAULT_NAME);

        if (!client.getNamespaces().contains(ns)) {`

ns is null.

**Comment by mdumanoj** [comment]
@MatCuk , I am facing the same issue. I receive packet type 12 from Android client. Did you find anything useful?
Do you know what does packet type 12 means?

**Comment by sumeet-singh04** [comment]
I am facing the same issue, when trying to connect to a particular namespace. But the connection is successful even after the exception occurs.

**Comment by wgzhxy** [comment]
me to,  I get packet type 15, why?

**Comment by Mairuis** [comment]
I get same number 12

**Comment by nicsor** [comment]
Seems to happen on binary data, which might be sent in a different packet, without the package type.

if you prepend the binary blob with b'\x04, so it's marked as a message from the client'.
`        data=b'\x04' + <rest of binary data>`
it should be received ok on the other side.

not sure yet if it's a client issue(though it happens in clients written in python and js) or a server issue(don't have issues on a python server). Did you guys find a workaround? ie. custom InPacketHandler or additional pipe to handle this case?

**Comment by nicsor** [comment]
![image](https://github.com/user-attachments/assets/a155aaeb-a1a5-4a1b-b6f5-73ac64d70b55)

simple way to reproduce from postman: send binary data, based on endianness, second byte is decoded as the packet type. in attached case 8

using: com.corundumstudio.socketio:netty-socketio:2.0.11
