### ISSUE TITLE
InPacketHandler : Error during data processing. Client sessionId: xxx, data:

### ISSUE THREAD

**Issue by patpatpat123** [mrniko/netty-socketio#713]
Hello Team,

First of all, a big thanks for this project, it is awesome.
I am using 

 <dependency>
            <groupId>com.corundumstudio.socketio</groupId>
            <artifactId>netty-socketio</artifactId>
            <version>1.7.17</version>
        </dependency>

and it is a very cool project.
Just one small issue:

2019-10-14  ERROR xxx.local --- [tLoopGroup-14-1] c.c.s.h.InPacketHandler                  : Error during data processing. Client sessionId: xxx, data: 
java.lang.IllegalStateException
	at com.corundumstudio.socketio.protocol.PacketType.valueOf(PacketType.java:48)
	at com.corundumstudio.socketio.protocol.PacketDecoder.readType(PacketDecoder.java:86)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:160)

This error will occur every time.

I tried troubleshooting, and for whatever client that sets an namespace, for instance, an iOS client:
  socket = manager.socket(forNamespace: namespace)

this error is reproducible 100%.

Can this be fixed please?
Thank you

**Comment by patpatpat123** [comment]
Hello, 

Bumping this up

**Comment by JackyChan** [comment]
maybe this can help you. https://github.com/mrniko/netty-socketio/issues/730#issuecomment-588699936
