### ISSUE TITLE
JKS - certificate_unknown(SSL)

### ISSUE THREAD

**Issue by xujingzhou** [mrniko/netty-socketio#813]
Why is it that no matter I use the self-signed JKS certificate generated or the JKS in the official website example, I always get the certificate error?  how to resolve it?

The code information as below:
  InputStream resourceAsStream = this.getClass().getResourceAsStream(keyStore);
  config.setKeyStore(resourceAsStream);
  config.setKeyStorePassword("12345678");

The error information as below:
[nioEventLoopGroup-3-1] ERROR com.corundumstudio.socketio.listener.DefaultExceptionListener - javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:299)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1089)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:912)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:782)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1049)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:972)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:911)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:268)

**Comment by xujingzhou** [comment]
Has anyone encountered the same problem? How is it solved?

**Comment by xujingzhou** [comment]
there must use a certificate to bind domain access.

e.g.
https://a.b.com:9660
