### ISSUE TITLE
集群环境下的多个socket服务启动，后台一直 Exception in thread "redisson-3-4" java.lang.NullPointerException

### ISSUE THREAD

**Issue by fengyoushuang** [mrniko/netty-socketio#882]
netty-socketio&redisson version:

<redisson.version>3.20.0</redisson.version>
<netty-socketio.version>1.7.23</netty-socketio.version>

---------------------------------------------------------------------------------------------------

redisson.yml:
singleServerConfig:
  address: "redis://${redis.host}:${redis.port}"
  password: "${redis.password}"
  clientName: null
  database: ${redis.database}
  idleConnectionTimeout: 60000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 50
  subscriptionConnectionMinimumIdleSize: 2
  subscriptionConnectionPoolSize: 100
  connectionMinimumIdleSize: 8
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
#threads: 0
#nettyThreads: 0

codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"

---------------------------------------------------------------------------------------------------

redissonConfig.java
    @Bean
    public RedissonClient redissonClient() throws IOException {
        Config redissonConfig = Config.fromYAML(new ClassPathResource("redisson.yml").getInputStream());
        redissonConfig.setLockWatchdogTimeout(10000L);
        RedissonClient redisson = Redisson.create(redissonConfig);
        return redisson;
    }

---------------------------------------------------------------------------------------------------

SocketServer.java

     @Autowired
    RedissonClient redisson;

    @Bean
    public SocketIOServer socketIoServer() {
        SocketConfig socketConfig = new SocketConfig();
        socketConfig.setTcpNoDelay(true);
        socketConfig.setSoLinger(0);
        socketConfig.setReuseAddress(true);
        socketConfig.setTcpKeepAlive(true);

        Configuration config = new Configuration();
        config.setOrigin(null);
        config.setHostname("0.0.0.0");
        config.setPort(8081);
        //设置最大的WebSocket帧内容长度限制
        config.setMaxFramePayloadLength(1024 * 1024);
        //设置最大HTTP内容长度限制
        config.setMaxHttpContentLength(1024 * 1024);
        // 协议升级超时时间（毫秒），默认10000。HTTP握手升级为ws协议超时时间
        config.setUpgradeTimeout(10000);
        // Ping消息间隔（毫秒），默认25000。客户端向服务器发送一条心跳消息间隔
        config.setPingInterval(5000);
        // Ping消息超时时间（毫秒），默认60000，这个时间间隔内没有接收到心跳消息就会发送超时事件
        config.setPingTimeout(60000);
        // 连接时出现异常的处理
        config.setExceptionListener(new SocketExceptionListener());
        config.setRandomSession(true);
        config.setSocketConfig(socketConfig);

        config.setStoreFactory(new RedissonStoreFactory(redisson));
        config.setAckMode(AckMode.MANUAL);
        config.setAuthorizationListener(handshakeData -> {
            //http://localhost:8081/mynprc?client=xxx&token=xxxxxx
            String client = handshakeData.getSingleUrlParam("client");
            String token = handshakeData.getSingleUrlParam("token");
            try {
                if (StringUtils.isBlank(client) || StringUtils.isBlank(token) || "null".equals(client) || "null".equals(token)) {
                    return false;
                }
                return true;
            } catch (Exception e) {
                log.error("Socket身份失效，重新认证，{}<=>{}", client, token);
                return false;
            }
        });
        server = new SocketIOServer(config);
        server.addPingListener(socketClient -> {
            if (socketClient != null && socketClient.isChannelOpen()) {
                     //. do something
            }
        });
        SocketIONamespace namespace = server.addNamespace("/mynprc");
        if (namespace != null) {
            namespace.addConnectListener(socketClient -> {
                if (socketClient != null && socketClient.isChannelOpen()) {
                    log.warn("@OnConnect：namespace={}, sessionId={}的用户【建立】Socket连接", socketClient.getNamespace().getName(), socketClient.getSessionId());
                }
            });
            namespace.addDisconnectListener(socketClient -> {
                if (socketClient != null) {
                    log.warn("@OnDisconnect：namespace={},  sessionId={}的用户【断开】Socket连接", socketClient.getNamespace().getName(),  socketClient.getSessionId());
                }
            });
        }
        return server;
    }

---------------------------------------------------------------------------------------------------

 Exception in thread "redisson-3-4" java.lang.NullPointerException
    at com.corundumstudio.socketio.store.pubsub.BaseStoreFactory$4.onMessage(BaseStoreFactory.java:71)
    at com.corundumstudio.socketio.store.pubsub.BaseStoreFactory$4.onMessage(BaseStoreFactory.java:66)
    at com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(RedissonPubSubStore.java:61)
    at com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(RedissonPubSubStore.java:57)
    at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
    at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:68)
    at org.redisson.client.handler.CommandPubSubDecoder$1.run(CommandPubSubDecoder.java:164)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
 Exception in thread "redisson-3-5" java.lang.NullPointerException
    at com.corundumstudio.socketio.store.pubsub.BaseStoreFactory$6.onMessage(BaseStoreFactory.java:93)
    at com.corundumstudio.socketio.store.pubsub.BaseStoreFactory$6.onMessage(BaseStoreFactory.java:88)
    at com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(RedissonPubSubStore.java:61)
    at com.corundumstudio.socketio.store.RedissonPubSubStore$1.onMessage(RedissonPubSubStore.java:57)
    at org.redisson.PubSubMessageListener.onMessage(PubSubMessageListener.java:79)
    at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:68)
    at org.redisson.client.handler.CommandPubSubDecoder$1.run(CommandPubSubDecoder.java:164)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)

**Comment by mrniko** [comment]
The problem is that namespace wasn't added with addNamespace() method

**Comment by fengyoushuang** [comment]
@mrniko 
> The problem is that namespace wasn't added with addNamespace() method

<img width="771" alt="image" src="https://user-images.githubusercontent.com/13325124/225800537-e8bdcaef-2e47-41a3-9a6e-27d0220d4774.png">

I have called the addNamespace method, but why is it not added? How to solve it? Thanks!
