### ISSUE TITLE
Error recurrent : DefaultPromise  Failed to notify a listener. Event loop shut down?

### ISSUE THREAD

**Issue by timactive** [mrniko/netty-socketio#91]
Hi,
I have recurrent error in my log but i not see if it have a consequence with application

``` java

2013-12-17 23:01:28,715 | ERROR | ool-30-thread-13 | DefaultPromise                   | til.internal.logging.Slf4JLogger  181 | 488 - io.netty.common - 4.0.13.Final | Failed to notify a listener. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:703)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:296)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:614)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:130)[488:io.netty.common:4.0.13.Final]
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)[489:io.netty.transport:4.0.13.Final]
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)[489:io.netty.transport:4.0.13.Final]
    at com.corundumstudio.socketio.transport.MainBaseClient.disconnect(MainBaseClient.java:115)[301:netty-socketio:1.5.5.SNAPSHOT]
    at com.corundumstudio.socketio.handler.HeartbeatHandler$2.run(HeartbeatHandler.java:65)[301:netty-socketio:1.5.5.SNAPSHOT]
    at com.corundumstudio.socketio.scheduler.CancelableScheduler$1.run(CancelableScheduler.java:50)[301:netty-socketio:1.5.5.SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)[:1.7.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_45]
    at java.lang.Thread.run(Thread.java:744)[:1.7.0_45]
2013-12-17 23:01:32,949 | ERROR | pool-30-thread-6 | DefaultPromise                   | til.internal.logging.Slf4JLogger  181 | 488 - io.netty.common - 4.0.13.Final | Failed to notify a listener. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:703)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:296)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:614)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:130)[488:io.netty.common:4.0.13.Final]
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)[489:io.netty.transport:4.0.13.Final]
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)[489:io.netty.transport:4.0.13.Final]
    at com.corundumstudio.socketio.transport.MainBaseClient.disconnect(MainBaseClient.java:115)[301:netty-socketio:1.5.5.SNAPSHOT]
    at com.corundumstudio.socketio.handler.HeartbeatHandler$2.run(HeartbeatHandler.java:65)[301:netty-socketio:1.5.5.SNAPSHOT]
    at com.corundumstudio.socketio.scheduler.CancelableScheduler$1.run(CancelableScheduler.java:50)[301:netty-socketio:1.5.5.SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)[:1.7.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_45]
    at java.lang.Thread.run(Thread.java:744)[:1.7.0_45]
2013-12-17 23:01:45,102 | ERROR | ool-30-thread-16 | DefaultPromise                   | til.internal.logging.Slf4JLogger  181 | 488 - io.netty.common - 4.0.13.Final | Failed to notify a listener. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
    at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:703)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:296)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:614)[488:io.netty.common:4.0.13.Final]
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:130)[488:io.netty.common:4.0.13.Final]
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)[489:io.netty.transport:4.0.13.Final]
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)[489:io.netty.transport:4.0.13.Final]
    at com.corundumstudio.socketio.transport.MainBaseClient.disconnect(MainBaseClient.java:115)[301:netty-socketio:1.5.5.SNAPSHOT]
    at com.corundumstudio.socketio.handler.HeartbeatHandler$2.run(HeartbeatHandler.java:65)[301:netty-socketio:1.5.5.SNAPSHOT]
    at com.corundumstudio.socketio.scheduler.CancelableScheduler$1.run(CancelableScheduler.java:50)[301:netty-socketio:1.5.5.SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)[:1.7.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_45]
    at java.lang.Thread.run(Thread.java:744)[:1.7.0_45]
```

**Comment by 15620879530** [comment]
0.0
